// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ozonva/ova-promise-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PromiseRepository is an autogenerated mock type for the PromiseRepository type
type PromiseRepository struct {
	mock.Mock
}

// GetPromiseByID provides a mock function with given fields: ctx, id
func (_m *PromiseRepository) GetPromiseByID(ctx context.Context, id uuid.UUID) (*domain.Promise, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Promise
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Promise); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Promise)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPromiseList provides a mock function with given fields: ctx, limit, offset
func (_m *PromiseRepository) GetPromiseList(ctx context.Context, limit uint64, offset uint64) ([]domain.Promise, error) {
	ret := _m.Called(ctx, limit, offset)

	var r0 []domain.Promise
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []domain.Promise); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Promise)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemovePromise provides a mock function with given fields: ctx, id
func (_m *PromiseRepository) RemovePromise(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SavePromise provides a mock function with given fields: ctx, promise
func (_m *PromiseRepository) SavePromise(ctx context.Context, promise *domain.Promise) error {
	ret := _m.Called(ctx, promise)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Promise) error); ok {
		r0 = rf(ctx, promise)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SavePromiseList provides a mock function with given fields: ctx, promises
func (_m *PromiseRepository) SavePromiseList(ctx context.Context, promises []domain.Promise) error {
	ret := _m.Called(ctx, promises)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Promise) error); ok {
		r0 = rf(ctx, promises)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
