// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ozonva/ova-promise-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Saver is an autogenerated mock type for the Saver type
type Saver struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Saver) Close() {
	_m.Called()
}

// Init provides a mock function with given fields:
func (_m *Saver) Init() {
	_m.Called()
}

// Save provides a mock function with given fields: promise
func (_m *Saver) Save(promise domain.Promise) error {
	ret := _m.Called(promise)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Promise) error); ok {
		r0 = rf(promise)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
