// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServerMetrics is an autogenerated mock type for the ServerMetrics type
type ServerMetrics struct {
	mock.Mock
}

// IncCreatePromiseCounter provides a mock function with given fields:
func (_m *ServerMetrics) IncCreatePromiseCounter() {
	_m.Called()
}

// IncCreatePromiseCounterByValue provides a mock function with given fields: value
func (_m *ServerMetrics) IncCreatePromiseCounterByValue(value float64) {
	_m.Called(value)
}

// IncDeletePromiseCounter provides a mock function with given fields:
func (_m *ServerMetrics) IncDeletePromiseCounter() {
	_m.Called()
}

// IncUpdatePromiseCounter provides a mock function with given fields:
func (_m *ServerMetrics) IncUpdatePromiseCounter() {
	_m.Called()
}
