// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePromiseHandlerServer is an autogenerated mock type for the UnsafePromiseHandlerServer type
type UnsafePromiseHandlerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPromiseHandlerServer provides a mock function with given fields:
func (_m *UnsafePromiseHandlerServer) mustEmbedUnimplementedPromiseHandlerServer() {
	_m.Called()
}
